train_configs:
  - configs/train_koniq_baseline.yaml
  - configs/train_koniq_stair.yaml
  - configs/train_koniq_hyper.yaml
  - configs/train_koniq_caqf.yaml
  - configs/train_koniq_caqf_no_attn.yaml
  - configs/train_koniq_tiny.yaml
  - configs/train_koniq_tiny_kd.yaml
  - configs/train_koniq_tiny_r18_kd_stageA.yaml
  - configs/train_koniq_tiny_r18_kd_stageB.yaml
  - configs/train_koniq_tiny_r34.yaml
  - configs/train_koniq_tiny_r34_kd_stageA.yaml
  - configs/train_koniq_tiny_r34_kd_stageB.yaml
eval_config: configs/eval_cross_dataset.yaml

