mode: tiny_r34
dataset: koniq
image_root: data
train_split: data/metas/koniq_train.json
val_split: data/metas/koniq_test.json
output_dir: outputs/koniq_tiny_r34_mse_srcc
epochs: 80
batch_size: 32
lr: 1e-4
optimizer: adamw
loss:
  type: mse_srcc
  alpha: 0.2
model:
  use_se: true
  hidden_dim1: 512
  hidden_dim2: 256
  dropout_p: 0.1
device: cuda
seed: 42

